version: '3.4'
# Other docker-compose examples in /examples

services:
  swag:
    environment:
      - CERTPROVIDER=${SWAG_CERTPROVIDER}
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - ${DOCKERCONFDIR}/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  esphome:
    image: esphome/esphome
    container_name: esphome
    network_mode: host
    volumes: 
      - ${DOCKERCONFDIR}/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    restart: always
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    ports:
      - ${DECONZ_PORT_801}:801
      - ${DECONZ_PORT_8443}:8443
      - ${DECONZ_PORT_5930}:5930
    volumes:
      - ${DOCKERCONFDIR}/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=801
      - DECONZ_WS_PORT=8443
      - DECONZ_VNC_PORT=5930
      - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
      - DECONZ_VNC_MODE=1
      - DEBUG_INFO=1
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Europe/Vienna
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
  redis:
    image: bitnami/redis
    container_name: redis
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATADIR}:/bitnami/redis/data
      - ${DOCKERCONFDIR}/redis:/opt/bitnami/etc/redis
    ports:
      - 6379:6379
    restart: always
    # onlyfans:
    #   image: DIGITALCRIMINAL/OnlyFans
    #   volumes: 
    #     - ${DOCKERCONFDIR}/onlyfans/.settings/usr/src/app.settings
    #     - ${DOCKERCONFDIR}/onlyfans/.profiles/usr/src/app.profiles
    #     - ${DOCKERCONFDIR}/onlyfans/.sites/usr/src/app.sites

  influxdb:
    image: influxdb
  homeassistant:
    volumes:
      - ${DOCKERCONFDIR}/homeassistant/.ssh:/root/.ssh
  mosquitto:
    user: ${PGID}:${PUID}
  nextcloud:
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    depends_on:
      - "mariadb"
      - "redis"
