version: '3.4'
# Other docker-compose examples in /examples

services:
#  minecraft:
#    container_name: minecraft
#    image: itzg/minecraft-server
#    ports: 
#      - "25565:25565"
#      - "25575:25575"
#    environment:
#      EULA: "TRUE"
#      GAMEMODE: survival
#      DIFFICULTY: normal
#      MEMORY: "4G"
#      VIEW_DISTANCE: 40
#      SNOOPER_ENABLED: "false"
#      OPS: "darkhenne"
#    volumes:
#      - "${DOCKERSHAREDDIR}/minecraft:/data"
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - "${DOCKERCONFDIR}/postgres:/var/lib/postgresql/data"
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - ${DOCKERCONFDIR}/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=801
      - DECONZ_WS_PORT=8443
      - DECONZ_VNC_PORT=5930
      - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
      - DECONZ_VNC_MODE=1
      - DEBUG_INFO=1
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=Europe/Vienna
  esphome:
    image: esphome/esphome
    container_name: esphome
    network_mode: host
    volumes: 
      - ${DOCKERCONFDIR}/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 6052:6052
      - 4443:443
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    restart: always
  node-red:
    image: nodered/node-red
    container_name: nodered
    network_mode: host
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    ports:
      - 1880:1880
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/nodered:/data
  redis:
    image: bitnami/redis
    container_name: redis
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATADIR}:/bitnami/redis/data
      - ${DOCKERCONFDIR}/redis:/opt/bitnami/etc/redis
    ports:
      - 6379:6379
    restart: always
  cloudflareddns:
    environment:
      CF_APITOKEN: FzDmRg0NgvNlyorTZYaKqkf9K1IoK04DeXmMeMcj
  influxdb:
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_USER=philipp
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DB=homeassistant
  telegraf:
    volumes:
    - ${DOCKERCONFDIR}/telegraf:/etc/telegraf
    depends_on:
      - "influxdb"
  pihole:
    image: mattbodholdt/docker-pi-hole
  rtorrentvpn:
    ports:
      - 18650:18650
      - 18650:18650/udp
    environment:
      - DEBUG=true
  homeassistant:
    depends_on:
      - "mariadb"
  nextcloud:
    depends_on:
      - "mariadb"
      - "redis"
