version: '3.4'

services:
  swag:
    environment:
      - CERTPROVIDER=${SWAG_CERTPROVIDER}
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip
  rtorrentvpn:
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ${DOCKERCONFDIR}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8082:8080
    environment:
      - TZ=${TZ}
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - "mosquitto"
  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /home/postgres/pgdata/data
    volumes:
      - ${DOCKERCONFDIR}/postgres:/home/postgres
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    user: 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT_80}
    ports:
      - ${PGADMIN_PORT_80}:80
    volumes:
    - pgadmin_data:/var/lib/pgadmin
  esphome:
    image: esphome/esphome
    container_name: esphome
    network_mode: host
    volumes: 
      - ${DOCKERCONFDIR}/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
    restart: always
  jellyfin:
    image: linuxserver/jellyfin:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ${DOCKERCONFDIR}/jellyfin/custom:/custom-cont-init.d:ro
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFDIR}/jellyseerr:/app/config
    restart: unless-stopped
  jfa-go:
    environment:
      - 'true'
    container_name: jfa-go
    ports:
      - '8056:8056'
      - '8057:8057'
    volumes:
      - ${DOCKERCONFDIR}/jfa-go:/data
      - ${DOCKERCONFDIR}/jellyfin:/jf
      - /etc/localtime:/etc/localtime:ro
    image: hrfee/jfa-go
  redis:
    image: bitnami/redis
    container_name: redis
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATADIR}:/bitnami/redis/data
      - ${DOCKERCONFDIR}/redis:/opt/bitnami/redis/mounted-etc/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6379:6379
    restart: always
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    volumes:
      - ${DOCKERCONFDIR}/homeassistant/.ssh:/root/.ssh
      - ${DOCKERCONFDIR}/homeassistant/custom:/custom-cont-init.d:ro
  mosquitto:
    user: ${PGID}:${PUID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
  nextcloud:
    image: linuxserver/nextcloud:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${DOCKERCONFDIR}/nextcloud/custom:/custom-cont-init.d:ro
      - ${DOCKERCONFDIR}/nextcloud/config:/config
    depends_on:
      - "postgres"
      - "redis"

volumes:
  pgadmin_data:
